version: '3.7'
services:
  dump1090-fa:
    build: ./dump1090-fa
    image: dump1090-fa
    devices:
      - "/dev/bus/usb"
    expose:
      - "30001"
      - "30002"
      - "30003"
      - "30004"
      - "30005"
      - "30104"
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - LAT=${LAT}
      - LON=${LON}
  piaware:
    build: ./piaware
    image: piaware
#    network_mode: "host" 
    environment:
      - FLIGHTAWARE_USER=${FLIGHTAWARE_USER}
      - FLIGHTAWARE_PASSWORD=${FLIGHTAWARE_PASSWORD}
      - FLIGHTAWARE_FEEDER_ID=${FLIGHTAWARE_FEEDER_ID}
#      - FLIGHTAWARE_FEEDER_ID=b8f4ecf9-9f50-4057-b708-3a5eb297147f
      - RECEIVER_HOST=${RECEIVER_HOST}
      - RECEIVER_PORT=${RECEIVER_PORT}
      - RECEIVER_MLAT_PORT=${RECEIVER_MLAT_PORT}
    depends_on:
      - dump1090-fa
  fr24feed:
    build: ./fr24feed
    image: fr24feed1
    environment:
      - RECEIVER_HOST=${RECEIVER_HOST}
      - RECEIVER_PORT=${RECEIVER_PORT}
      - FR24_KEY=${FR24_KEY}
    ports:
      - "8754:8754"
    depends_on:
      - dump1090-fa
